- name: vscode - Install vscode
  shell:
    cmd: |
      # add repo and signing key
      sudo apt-get install wget gpg -y
      wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
      sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
      sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
      # rm -f packages.microsoft.gpg
      # update package cache
      sudo apt install apt-transport-https -y
      # install
      sudo apt update
      sudo apt install code -y # or code-insiders
    tags:
      - vscode
      - full
